# Generated by Django 5.2.7 on 2025-10-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0005_permission_permissiongroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='backup_codes',
            field=models.TextField(blank=True, help_text='JSON string of backup codes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
