# Generated by Django 4.2 on 2025-10-15 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0007_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='bin_location',
            field=models.CharField(blank=True, help_text='Bin/shelf location within the warehouse', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='effective_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Date when current prices became effective'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_wholesale_qty',
            field=models.PositiveIntegerField(default=1, help_text='Minimum quantity for wholesale pricing'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for the product', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
