# Generated by Django 4.2 on 2025-10-15 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0008_inventory_bin_location_product_effective_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferline',
            name='from_inventory',
            field=models.ForeignKey(blank=True, help_text='Specific inventory item to transfer from (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_out_lines', to='pos_app.inventory'),
        ),
        migrations.AddField(
            model_name='transferline',
            name='to_inventory',
            field=models.ForeignKey(blank=True, help_text='Specific inventory item to transfer to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_in_lines', to='pos_app.inventory'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('warehouse', 'Warehouse'), ('store', 'Store Location'), ('distribution_center', 'Distribution Center'), ('depot', 'Depot')], default='warehouse', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='bin_location',
            field=models.CharField(blank=True, help_text='Legacy bin location field (deprecated in favor of Bin model)', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(help_text='Warehouse/Store where this inventory is located', on_delete=django.db.models.deletion.CASCADE, to='pos_app.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Maximum capacity in units or volume'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(help_text='Address or general location of the warehouse/store', max_length=255),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the location (e.g., Aisle A, Section 1, Back Room)', max_length=255)),
                ('code', models.CharField(help_text='Unique code for the location (e.g., A-01, SEC-001)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the location')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Maximum capacity for this location')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_location', models.ForeignKey(blank=True, help_text='Parent location if this is a sub-location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_locations', to='pos_app.location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='pos_app.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'ordering': ['warehouse', 'code'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bin (e.g., Shelf 1, Bin A-01)', max_length=255)),
                ('code', models.CharField(help_text='Unique code for the bin (e.g., B-01-01)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the bin')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Maximum capacity for this bin')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='pos_app.location')),
            ],
            options={
                'verbose_name_plural': 'Bins',
                'ordering': ['location', 'code'],
                'unique_together': {('location', 'code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='goodsreceivednoteline',
            name='destination_bin',
            field=models.ForeignKey(blank=True, help_text='Specific destination bin for this received item (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_app.bin'),
        ),
        migrations.AddField(
            model_name='goodsreceivednoteline',
            name='destination_location',
            field=models.ForeignKey(blank=True, help_text='Specific destination location for this received item (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_app.location'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='bin',
            field=models.ForeignKey(blank=True, help_text='Specific bin/shelf within the location (optional, for advanced tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='pos_app.bin'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Specific location within the warehouse (optional, for advanced tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='pos_app.location'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='destination_bin',
            field=models.ForeignKey(blank=True, help_text='Destination bin within location (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_app.bin'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='destination_location',
            field=models.ForeignKey(blank=True, help_text='Destination location within warehouse (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_app.location'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='destination_bin',
            field=models.ForeignKey(blank=True, help_text='Destination bin for this item (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_app.bin'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='destination_location',
            field=models.ForeignKey(blank=True, help_text='Destination location for this item (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_app.location'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_bin',
            field=models.ForeignKey(blank=True, help_text='Source bin within the location (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='pos_app.bin'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_location',
            field=models.ForeignKey(blank=True, help_text='Source location within the warehouse (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='pos_app.location'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_bin',
            field=models.ForeignKey(blank=True, help_text='Destination bin within the location (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='pos_app.bin'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_location',
            field=models.ForeignKey(blank=True, help_text='Destination location within the warehouse (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='pos_app.location'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'variant', 'warehouse', 'location', 'bin')},
        ),
    ]
