# Generated by Django 4.2 on 2025-10-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0009_transferline_from_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='code',
            field=models.CharField(help_text='Unique code for the bin within the location (e.g., B-01-01)', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(help_text='Unique code for the location within the warehouse (e.g., A-01, SEC-001)', max_length=50),
        ),
    ]
