# Generated by Django 4.2 on 2025-10-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0010_alter_bin_code_alter_location_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='store_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='store_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
