# Generated by Django 4.2 on 2025-10-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0011_customer_store_credit_userprofile_store_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the customer'),
        ),
    ]
