# Generated by Django 4.2 on 2025-10-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0013_ecommerceplatform_paymentgatewayconfig_webhook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='backup_codes',
            field=models.TextField(blank=True, help_text='JSON string of backup codes', null=True),
        ),
    ]
